server:
  error:
    include-stacktrace: never
  port: 5000

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
        trace: false

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;;DATABASE_TO_UPPER=false
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


logging:
  level:
    org.hibernate.SQL: debug

default-upload-image-directory: src/main/resources/upload/image/